"""initial schema

Revision ID: fe8f26727bce
Revises: 
Create Date: 2026-03-27 13:58:15.590981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe8f26727bce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='America/New_York', nullable=False),
    sa.Column('daily_push_hour', sa.SmallInteger(), server_default='9', nullable=False),
    sa.Column('daily_word_count', sa.SmallInteger(), server_default='5', nullable=False),
    sa.Column('difficulty_level', sa.String(length=10), server_default='B2-C1', nullable=False),
    sa.Column('skip_triage', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('words',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=200), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('definitions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('translation_ru', sa.String(length=500), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('antonyms', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('difficulty_band', sa.String(length=10), nullable=True),
    sa.Column('is_enriched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_difficulty_band'), 'words', ['difficulty_band'], unique=False)
    op.create_index(op.f('ix_words_frequency_rank'), 'words', ['frequency_rank'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    op.create_table('daily_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('triage_word_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('selected_word_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('known_word_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('daily_word_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', name='uq_daily_sessions_user_date')
    )
    op.create_table('user_words',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='learning', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='daily', nullable=False),
    sa.Column('fsrs_card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fsrs_state', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_words_user_word')
    )
    op.create_index('ix_user_words_user_due', 'user_words', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_user_words_user_id'), 'user_words', ['user_id'], unique=False)
    op.create_index('ix_user_words_user_status', 'user_words', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_words_word_id'), 'user_words', ['word_id'], unique=False)
    op.create_table('word_pool',
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'source', name='uq_word_pool_word_source')
    )
    op.create_index(op.f('ix_word_pool_source'), 'word_pool', ['source'], unique=False)
    op.create_table('review_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_word_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_type', sa.String(length=20), nullable=False),
    sa.Column('fsrs_log_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_days', sa.Float(), nullable=True),
    sa.Column('elapsed_days', sa.Float(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_word_id'], ['user_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    op.create_index('ix_review_logs_user_reviewed', 'review_logs', ['user_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_review_logs_user_word_id'), 'review_logs', ['user_word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_user_word_id'), table_name='review_logs')
    op.drop_index('ix_review_logs_user_reviewed', table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_word_pool_source'), table_name='word_pool')
    op.drop_table('word_pool')
    op.drop_index(op.f('ix_user_words_word_id'), table_name='user_words')
    op.drop_index('ix_user_words_user_status', table_name='user_words')
    op.drop_index(op.f('ix_user_words_user_id'), table_name='user_words')
    op.drop_index('ix_user_words_user_due', table_name='user_words')
    op.drop_table('user_words')
    op.drop_table('daily_sessions')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index(op.f('ix_words_frequency_rank'), table_name='words')
    op.drop_index(op.f('ix_words_difficulty_band'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
